### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ColinGilbert** [VincentToups/scran#1]
Hi,

First of all, thanks for releasing this awesome code; I love Gambit and would like to put it at the core of my game programming. However, my main fear is that using unlicensed code may come back and harm me. Could you license this code under a liberal (preferably non-viral license) please?

Thanks!
Colin

**Comment by VincentToups** [comment]
Hi Colin,

Great suggestion - I've just pushed a version with the MIT License.  Let me know if that isn't permissive enough, I'd be happy to change it.
